name: Build and deploy documentation site for the repository to GitHub Pages

on:
  push:
    branches:
      - 'main'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Graphviz (dot)
        run: sudo apt update && sudo apt install -y graphviz
      - name: Install MkDocs
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material
      - name: Configure Pages
        uses: actions/configure-pages@v5
      - name: Build the templates
        run: mvn -B package -am -pl templates -DskipTests
      - name: Generate diagrams from the templates
        run: java -jar templates/target/templates-0.3.0-SNAPSHOT.jar
      - name: Build Pages
        run: mkdocs build
      - name: Upload Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site/'

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
